version: '3.8'

services:
  db:
    image: postgres:16.4
    container_name: portfolio_postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: user01
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    environment:
      POSTGRES_USER: user01
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/portfolio
    tty: true
    stdin_open: true
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres_volume:
